name: 'env'
description: 'Setup environment, credentials, and common tools'

inputs:
  python-version:
    description: Python version to install
  extra-apt-packages:
    description: Extra apt packages to install
    default: ""
  secrets:
    description: Secrets toJSON

runs:
  using: "composite"
  steps:
    - name: apply.environment
      uses: exodigo/exodigo_ci_actions_apply-environment@s1
      with:
        secrets: ${{ inputs.secrets }}

    - name: install.python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: install.base
      env:
        DEBIAN_FRONTEND: noninteractive
        TZ: Etc/UTC
      shell: sh
      run: |
        sudo apt install -y apt ${{ inputs.extra-apt-packages }}
        sudo apt install -y apt ${OCI_ENGINE}

    - name: config.aws
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: ${{ env.AWS_ROLE_REGION }}
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        mask-aws-account-id: 'no'

    - name: config.tools
      shell: sh
      run: |
        for tool in pip twine npm; do
          aws codeartifact login \
              --region "${AWS_CODEARTIFACT_REGION}" \
              --domain "${AWS_CODEARTIFACT_CI_DOMAIN_NAME}" \
              --repository "${AWS_CODEARTIFACT_CI_REPOSITORY_NAME}" \
              --tool "${tool}"
        done
        pip config set global.extra-index-url https://pypi.python.org/simple/
        aws ecr get-login-password --region "${AWS_ROLE_REGION}" | ${OCI_ENGINE} login --username AWS --password-stdin "${AWS_ECR_NAME}"
