name: 'build-container-by-artifact'
description: 'Build and publish a container for an artifact'

inputs:
  container_name:
    description: The name of the container
    required: true
  artifact_name:
    description: The name of the artifact
    required: true
  artifact_version:
    description: The version of the artifact
    required: true
  stable_version:
    description: The stable version of the artifact.
    default: ""
  publish:
    description: Whether or not to publish the container (The temporary tag is published regardless)
    default: "true"
outputs:
  container:
    description: The created container
    value: ${{ steps.build.outputs.container }}
  tags:
    description: The tags created for the container
    value: ${{ steps.build.outputs.tags }}

runs:
  using: "composite"
  steps:
    - name: extract.oidc
      uses: exodigo/exodigo_github-action-oidc@v1
      id: oidc

    - name: checkout.exodigo-containers
      uses: actions/checkout@v3
      with:
        path: exodigo-containers
        repository: ${{ steps.oidc.outputs.job_workflow_repo_name_and_owner }}
        ref: ${{ steps.oidc.outputs.job_workflow_repo_ref }}

    - name: env.setup
      uses: ./exodigo-containers/.github/actions/build-container
      with:
        container_name: ${{ inputs.container_name }}
        tag_names: ${{ inputs.artifact_version }} ${{ inputs.stable_version }}
        container_input: |
          OCI_ARG_NAME="--build-arg=ARTIFACT_NAME=${{ inputs.artifact_name }}"
          OCI_ARG_VERSION="--build-arg=ARTIFACT_VERSION=${{ inputs.artifact_version }}"
        publish: ${{ inputs.publish }}
