name: 'build-python-artifact-container'
description: 'Build and publish a container for a python package'

inputs:
  container_name:
    description: The name of the container
    required: true
  artifact_name:
    description: The name of the artifact
    required: true
  artifact_version:
    description: The version of the artifact
    required: true
  stable_version:
    description: The stable version of the artifact.
    default: ""
  container_input:
    description: Input for Containerfile
    default: ""
  publish:
    description: Whether or not to publish the container (The temporary tag is published regardless)
    default: "true"
outputs:
  container:
    description: The created container
    value: ${{ steps.build.outputs.container }}
  tags:
    description: The tags created for the container
    value: ${{ steps.build.outputs.tags }}

runs:
  using: "composite"
  steps:
    - name: set.exodigo-containers-actions
      shell: sh
      run: |
        ln -s "${{ github.action_path }}/.." exodigo-containers-actions || true

    - name: build.container
      uses: ./exodigo-containers-actions/build-container-by-artifact
      with:
        container_name: ${{ inputs.container_name }}
        artifact_name: ${{ inputs.artifact_name }}
        artifact_version: ${{ inputs.artifact_version }}
        stable_version: ${{ inputs.stable_version }}
        container_input: |
          OCI_ARG_PIP_SECRET_ID="--secret id=pip_secret,src=${HOME}/.config/pip/pip.conf"
          OCI_ARG_PIP_SECRET_ID="--build-arg=pip_creds=.config/pip/pip.conf"
          ${{ inputs.container_input }}
        publish: ${{ inputs.publish }}
