name: 'build-versioned-container'
description: 'Build and publish a container with version tags'

inputs:
  container_name:
    description: The name of the container
    required: true
  working_directory:
    description: The desired working directory
    default: "."
  container_input:
    description: Input for Containerfile
    default: ""
  publish:
    description: Whether or not to publish the container (The temporary tag is published regardless)
    default: "true"
outputs:
  container:
    description: The created container
    value: ${{ steps.build.outputs.container }}
  tags:
    description: The tags created for the container
    value: ${{ steps.build.outputs.tags }}

runs:
  using: "composite"
  steps:
    - name: set.exodigo-containers-actions
      shell: sh
      run: |
        . "${{ github.action_path }}/../.action"
        if ! [ -d "${action_repo}" ]; then
          ln -sfn "${{ github.action_path }}/.." "${action_repo}"
        fi

    - name: env.version
      id: version
      uses: ./exodigo-containers-actions/calculate-version
      with:
        working_directory: ${{ inputs.working_directory }}

    - name: prepare.tag_names
      id: tag_names
      shell: sh
      run: |
        tag_names=${{ steps.version.outputs.version }}
        if [ "${{ steps.version.outputs.ci_phase }}" = "tag" ]; then
          tag_names="${tag_names} ${{ steps.version.outputs.version_y_stream }}"
        fi
        cat >> "${GITHUB_OUTPUT}" << __EOF__
        tag_names=${tag_names}
        __EOF__

    - name: build.container
      uses: ./exodigo-containers-actions/build-container
      with:
        container_name: ${{ inputs.container_name }}
        tag_names: ${{ steps.tag_names.outputs.tag_names }}
        container_file: ${{ inputs.container_file }}
        working_directory: ${{ inputs.working_directory }}
        container_input: ${{ inputs.container_input }}
        publish: ${{ inputs.publish }}
