name: 'build-versioned-container'
description: 'Build and publish a container with version tags'

inputs:
  container_alias:
    description: The name of the container
    required: true
  working-directory:
    description: The desired working directory
    default: "."
  container_input:
    description: Input for Containerfile
    default: ""
  publish:
    description: Whether or not to publish the container (The temporary container name is published regardless)
    default: "true"
outputs:
  container:
    description: The created container
    value: ${{ steps.build.outputs.container }}
  container_names:
    description: Additional names created for the container
    value: ${{ steps.build.outputs.container_names }}

runs:
  using: "composite"
  steps:
    - name: set.exodigo-containers-actions
      shell: sh
      run: |
        . "${{ github.action_path }}/../.action"
        if ! [ -d "${action_repo}" ]; then
          ln -sfn "${{ github.action_path }}/.." "${action_repo}"
        fi

    - name: env.version
      id: version
      uses: exodigo/exodigo_ci_common/actions/gen-version@s1
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: prepare.names
      id: names
      shell: sh
      run: |
        container_names=${{ steps.version.outputs.version }}
        if [ "${{ steps.version.outputs.ci_phase }}" = "tag" ]; then
          container_names="${container_names} ${{ steps.version.outputs.version_y_stream }}"
        fi
        cat >> "${GITHUB_OUTPUT}" << __EOF__
        container_names=${container_names}
        __EOF__

    - name: build.container
      id: build
      uses: ./exodigo-containers-actions/build-container
      with:
        container_alias: ${{ inputs.container_alias }}
        container_names: ${{ steps.names.outputs.container_names }}
        container_file: ${{ inputs.container_file }}
        working-directory: ${{ inputs.working-directory }}
        container_input: ${{ inputs.container_input }}
        publish: ${{ inputs.publish }}
