name: 'generate-tags'
description: 'Generate full container tags for later usage'

inputs:
  container_name:
    description: The name of the container to generate a tag for
    required: true
  tag_names:
    description: Tag names to generate tags for
    default: ""
outputs:
  tags:
    description: The generated tags
    value: ${{ steps.tags.outputs.tags }}

runs:
  using: "composite"
  steps:
    - name: set.tags
      id: tags
      shell: sh
      run: |
        if [ -z "${{ inputs.tag_names}}" ]; then
          tags=""
        else
          tags="$(printf "${AWS_ECR_NAME}/${AWS_ECR_CI_REPOSITORY_NAME}/${{ inputs.container_name }}:%s " ${{ inputs.tag_names }})"
        fi
        cat >> "${GITHUB_OUTPUT}" << __EOF__
        tags=${tags}
        __EOF__
