name: 'tag-container'
description: 'Adds tags to a given container and publish them'

inputs:
  container:
    description: The container to publish
    required: true
  is_local:
    description: Whether or not the container is local
    default: "false"
  tags:
    description: The tags to add for the container
    default: ""

runs:
  using: "composite"
  steps:
  - name: container.publish
    shell: sh
    run: |
      if [ "${{ inputs.is_local }}" == "false" ]; then
        ${OCI_ENGINE} pull "${{ inputs.container }}"
      fi
      tags="${{ inputs.tags }}"
      for t in ${tags}; do
        ${OCI_ENGINE} tag "${{ inputs.container }}" "${t}"
        ${OCI_ENGINE} push "${t}"
      done
