name: 'build-base-container'
description: 'Build and publish a basic container'

inputs:
  container_name:
    description: The name of the container
    required: true
  tag_names:
    description: Tag names to generate tags for
    default: ""
  container_file:
    description: Name of the file to use for build
    default: "Containerfile"
  working_directory:
    description: Working directory during build
    default: "."
  container_input:
    description: Input for Containerfile
    default: ""
  publish:
    description: Whether or not to publish the container (The temporary tag is published regardless)
    default: "true"
outputs:
  temp_tag:
    description: The temporary tag given to the container
    value: '${{ steps.tags.outputs.temp_tag }}'
  tags:
    description: The tags created for the container
    value: '${{ steps.tags.outputs.tags }}'

runs:
  using: "composite"
  steps:
    - name: generate.tags
      id: tags
      uses: exodigo/eli-public-test/.github/actions/generate-tags@master
      with:
        container_name: ${{ inputs.container_name }}
        tag_names: ${{ inputs.tag_names }}

    - name: container.build
      uses: exodigo/eli-public-test/.github/actions/build-container@master
      with:
        container_file: ${{ inputs.container_file }}
        working_directory: ${{ inputs.working_directory }}
        container_tag: ${{ steps.tags.outputs.temp_tag }}
        container_input: ${{ inputs.container_input }}

    - name: prepare.final.tags
      id: prepare
      shell: sh
      run: |
        tags="${{ steps.tags.outputs.temp_tag }}"
        if [ "${{ inputs.publish}}" = "true" ]; then
          tags="${tags} ${{ steps.tags.outputs.tags }}"
        fi
        cat >> "${GITHUB_OUTPUT}" << __EOF__
        final_tags=${tags}
        __EOF__

    - name: container.publish.all
      uses: exodigo/eli-public-test/.github/actions/tag-container@master
      with:
        container: ${{ steps.tags.outputs.temp_tag }}
        tags: ${{ steps.prepare.outputs.final_tags }}
