name: 'container-env'
description: 'Setup container environment'

inputs:
  working-directory:
    description: The desired working directory
    default: "."
  secrets:
    description: Secrets toJSON

runs:
  using: "composite"
  steps:
    - name: config.env
      if: ${{ env.__CI_CONTAINER_ENV_SET }} != "true"
      uses: exodigo/exodigo_ci_common/actions/ci-env@s1
      with:
        working-directory: ${{ inputs.working-directory }}
        secrets: ${{ inputs.secrets }}

    - name: install.oci_engine
      if: ${{ env.__CI_CONTAINER_ENV_SET }} != "true"
      env:
        DEBIAN_FRONTEND: noninteractive
        TZ: Etc/UTC
      shell: sh
      run: |
        sudo apt install -y apt ${OCI_ENGINE}

    - name: set.lock
      if: ${{ env.__CI_CONTAINER_ENV_SET }} != "true"
      shell: sh
      run: |
        cat >> "${GITHUB_ENV}" << __EOF__
        __CI_CONTAINER_ENV_SET=true
        __EOF__
