name: 'container-env'
description: 'Setup container environment'

inputs:
  working-directory:
    description: The desired working directory
    default: "."
  secrets:
    description: Secrets toJSON

runs:
  using: "composite"
  steps:
    - name: config.env
      if: ${{ env.CI_CONTAINER_ENV_SET }} != "true"
      uses: exodigo/exodigo_ci_common/actions/ci-env@test
      with:
        working_directory: ${{ inputs.working_directory }}
        secrets: ${{ inputs.secrets }}

    - name: install.oci_engine
      if: ${{ env.CI_CONTAINER_ENV_SET }} != "true"
      env:
        DEBIAN_FRONTEND: noninteractive
        TZ: Etc/UTC
      shell: sh
      run: |
        sudo apt install -y apt ${OCI_ENGINE}

    - name: config.ci_engine
      if: ${{ env.CI_CONTAINER_ENV_SET }} != "true"
      shell: sh
      run: |
        aws ecr get-login-password --region "${AWS_ROLE_REGION}" | ${OCI_ENGINE} login --username AWS --password-stdin "${AWS_ECR_NAME}"

    - name: set.ci_container_env
      if: ${{ env.CI_CONTAINER_ENV_SET }} != "true"
      shell: sh
      run: |
        cat >> "${GITHUB_ENV}" << __EOF__
        CI_CONTAINER_ENV_SET=true
        __EOF__
