name: 'push-container'
description: 'Add container names to a given container and publish them'

inputs:
  container:
    description: The container to publish
    required: true
  container_names:
    description: The container names to add for the container
    default: ""

runs:
  using: "composite"
  steps:
  - name: container.publish
    shell: sh
    run: |
      if ! ${OCI_ENGINE} image exists "${{ inputs.container }}"; then
        ${OCI_ENGINE} image pull "${{ inputs.container }}"
      fi
      for name in ${{ inputs.container_names }}; do
        ${OCI_ENGINE} image tag "${{ inputs.container }}" "${name}"
        ${OCI_ENGINE} image push "${name}"
      done
