name: 'push-container'
description: 'Add tags to a given container and publish them'

inputs:
  container:
    description: The container to publish
    required: true
  tags:
    description: The tags to add for the container
    default: ""

runs:
  using: "composite"
  steps:
  - name: container.publish
    shell: sh
    run: |
      if ! ${OCI_ENGINE} image exists "${{ inputs.container }}"; then
        ${OCI_ENGINE} image pull "${{ inputs.container }}"
      fi
      for t in ${{ inputs.tags }}; do
        ${OCI_ENGINE} image tag "${{ inputs.container }}" "${t}"
        ${OCI_ENGINE} image push "${t}"
      done
