name: 'calculate-version'
description: 'Calculates version based on version.txt and CI phase'

inputs:
  working_directory:
    description: The desired working directory
    default: "."
outputs:
  ci-phase:
    description: 'CI phase: review, branch, tag'
    value: ${{ steps.version.outputs.ci-phase }}
  version:
    description: Calculated version
    value: ${{ steps.version.outputs.version }}
  version_y_stream:
    description: Calculated version y stream
    value: ${{ steps.version.outputs.version_y_stream }}

runs:
  using: "composite"
  steps:
    - name: env.version
      id: version
      working-directory: ${{ inputs.working_directory }}
      shell: sh
      run: |
        version="$(cat version.txt | sed 's/-.*//')"
        case "${{ github.event.ref }}" in
          refs/remotes/pull/*|refs/heads/gerrit/*)
            ci_phase=review
            version="${version}-dev-${{ github.run_number }}"
            ;;
          refs/tags/*)
            ci_phase=tag
            ;;
          *)
            ci_phase=branch
            version="${version}-a-${{ github.run_number }}"
            ;;
        esac

        version_y_stream="$(echo ${version} | awk -F. '{print $1 "." $2}')"
        echo "${version}" > version.txt
        echo "VERSION: ${version}"
        echo "VERSION_Y_STREAM: ${version_y_stream}"

        cat >> "${GITHUB_OUTPUT}" << __EOF__
        ci-phase=${ci_phase}
        version=${version}
        version_y_stream=${version_y_stream}
        __EOF__
