name: 'build-container'
description: 'Build a container'

inputs:
  container_file:
    description: Name of the file to use for build
    default: "Containerfile"
  working_directory:
    description: Working directory during build
    default: "."
  container_tag:
    description: The tag to give the container
    required: true
  container_input:
    description: Input for Containerfile
    default: ""
outputs:
  temp_tag:
    description: A temporary tag of the built container
    value: ${{ steps.build.outputs.temp_tag }}

runs:
  using: "composite"
  steps:
    - name: container.build
      id: build
      shell: sh
      working-directory: ${{ inputs.working_directory }}
      env:

        OCI_CONTAINER_FILE: ${{ inputs.container_file }}
      run: |
        temp_tag="${AWS_ECR_NAME}/${AWS_ECR_CI_REPOSITORY_NAME}/${AWS_ECR_CI_TEMPORARY_REPOSITORY}:temp-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}-$(date -u +%s)"
        OCI_ARG_LOCAL_TAG="--tag=${temp_tag}"
        eval "${{ inputs.container_input }}"
        "${{ github.action_path }}/build-container.sh"
        cat >> "${GITHUB_OUTPUT}" << __EOF__
        temp_tag=${temp_tag}
        __EOF__
