name: 'build-container'
description: 'Build and publish a basic container'

inputs:
  container_name:
    description: The name of the container
    required: true
  tag_names:
    description: Tag names to generate tags for
    default: ""
  container_file:
    description: Name of the file to use for build
    default: "Containerfile"
  working_directory:
    description: Working directory during build
    default: "."
  container_input:
    description: Input for Containerfile
    default: ""
  publish:
    description: Whether or not to publish the container (The temporary tag is published regardless)
    default: "true"
outputs:
  container:
    description: The created container
    value: ${{ steps.build.outputs.container }}
  tags:
    description: Additional tags created for the container
    value: ${{ steps.tags.outputs.tags }}

runs:
  using: "composite"
  steps:
    - name: set.exodigo-containers-actions
      shell: sh
      run: |
        . "${{ github.action_path }}/../.action"
        if ! [ -d "${action_repo}" ]; then
          ln -sfn "${{ github.action_path }}/.." "${action_repo}"
        fi

    - name: generate.tags
      id: tags
      uses: ./exodigo-containers-actions/generate-tags
      with:
        container_name: ${{ inputs.container_name }}
        tag_names: ${{ inputs.tag_names }}

    - name: container.build
      id: build
      shell: sh
      working-directory: ${{ inputs.working_directory }}
      env:
        OCI_CONTAINER_FILE: ${{ inputs.container_file }}
      run: |
        container="${AWS_ECR_NAME}/${AWS_ECR_CI_REPOSITORY_NAME}/${AWS_ECR_CI_TEMPORARY_REPOSITORY}:temp-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}-$(date -u +%s)"
        eval "${{ inputs.container_input }}"
        OCI_ARG_LOCAL_TAG="--tag=${container}"
        set | sed -n -e 's/^\(OCI_ARG_\)=.*/\1/ p'
        for x in $(set | sed -n -e 's/^\(OCI_ARG_[^=]*\)=.*/\1/ p'); do
          eval "export ${x}"
        done
        "${{ github.action_path }}/build-container.sh"
        cat >> "${GITHUB_OUTPUT}" << __EOF__
        container=${container}
        __EOF__

    - name: prepare.final.tags
      id: prepare
      shell: sh
      run: |
        tags="${{ steps.build.outputs.container }}"
        if [ "${{ inputs.publish}}" = "true" ]; then
          tags="${tags} ${{ steps.tags.outputs.tags }}"
        fi
        cat >> "${GITHUB_OUTPUT}" << __EOF__
        final_tags=${tags}
        __EOF__

    - name: container.publish.all
      uses: ./exodigo-containers-actions/push-container
      with:
        container: ${{ steps.build.outputs.container }}
        tags: ${{ steps.prepare.outputs.final_tags }}
