name: 'build-container'
description: 'Build a container'

inputs:
  container_file:
    description: Path to the Containerfile
    required: true
  container_tag:
    description: The tag to give the container
    required: true
  container_input:
    description: Input for Containerfile
    default: ""

runs:
  using: "composite"
  steps:
    - name: container.build
      shell: sh
      env:
        OCI_ARG_LOCAL_TAG: --tag=${{ inputs.container_tag }}
        OCI_CONTAINER_FILE: ${{ inputs.container_file }}
      run: |
        eval "${{ inputs.container_input }}"
        "${{ github.action_path }}/build-container.sh"
