name: build-base-container

on:
  workflow_call:
    inputs:
      container_name:
        description: The name of the container
        type: string
        required: true
      container_input:
        description: Input for Containerfile
        type: string
        default: ""

jobs:
  build:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-22.04

    steps:
      - name: apply.environment
        uses: exodigo/exodigo_ci_actions_apply-environment@s1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: extract.oidc
        uses: exodigo/exodigo_github-action-oidc@v1
        id: oidc

      - name: checkout.eli-public-test
        uses: actions/checkout@v3
        with:
          path: eli-public-test
          repository: ${{ steps.oidc.outputs.job_workflow_repo_name_and_owner }}
          ref: ${{ steps.oidc.outputs.job_workflow_repo_ref }}

      - name: generate.tags
        id: tags
        uses: ./eli-public-test/.github/actions/generate-tags
        with:
          container_name: ${{ inputs.container_name }}
          tag_names: latest
          secrets: ${{ toJSON(secrets) }}

      - name: container.build
        uses: ./eli-public-test/.github/actions/build-container
        with:
          container_tags: ${{ steps.tags.outputs.temp_tag }}
          container_input: ${{ inputs.container_input }}
