name: build-base-container

on:
  workflow_call:
    inputs:
      container_name:
        description: The name of the container
        type: string
        required: true
      container_input:
        description: Input for Containerfile
        type: string
        default: ""

jobs:
  build:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-22.04

    steps:
      - name: apply.environment
        uses: exodigo/exodigo_ci_actions_apply-environment@s1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: generate.tags
        id: tags
        uses: exodigo/eli-public-test/.github/workflows/generate-tags.yml@master
        with:
          container_name: ${{ inputs.container_name }}
          tag_names: latest
          secrets: ${{ toJSON(secrets) }}

      - name: container.build
        uses: exodigo/eli-public-test/.github/workflows/build-container.yml@master
        with:
          container_tags: ${{ steps.tags.outputs.tags }}
          container_input: ${{ inputs.container_input }}
